### ISSUE TITLE
unsatisfiable ALL_INIT

### ISSUE THREAD

**Issue by johnyf** [tulip-control/gr1c#27]
Mathematically, the option `-n ALL_INIT` is:

``` tla
\A x, y:  Init(x, y) => WinningSet(x, y)
```

This formula is valid if `Init \equiv FALSE`. However, the result in this case is not useful, and the specification most certainly contains some unintended error. Raising an error would be equivalent to modifying the above definition to:

``` tla
/\ \E x, y:  Init(x, y)
/\ \A x, y:  Init(x, y) => WinningSet(x, y)
```

At this time, I have not formed an opinion as to whether the definition should be modified. Simple is better than complex, so the first definition would probably better remain as is for now. Nevertheless, it would be good to provide a warning message if `Init` is found to be unsatisfiable.

A small example:

```
# spec.txt
ENV: x;
SYS: y;

ENVINIT: y;
ENVGOAL: []<>x;

SYSINIT: False;
SYSTRANS: [](y' <-> x);
SYSGOAL: []<>!y;
```

with:

`gr1c -v -n ALL_INIT spec.txt`

**Comment by slivingston** [comment]
The failure that occurs from trying your example is surprising:
```sh
% gr1c -n ALL_INIT spec.spc
synthesize, realloc: Success
```
Internally, `gr1c` detects a return value of `NULL` from `realloc()`, which in context is an error, so it quits quickly using `exit(-1)`. However, `perror()` describes it as "Success" because `realloc()` was called with size 0.

**Comment by slivingston** [comment]
Independently of the initial condition, is your example realizable? My reasoning:

1. `x` can eventually have fixed value TRUE,
2. therefore, `y` must eventually always have value TRUE,
3. therefore, no play for any strategy can satisfy []<>!y.

**Comment by johnyf** [comment]
No, with initial conditions `TRUE`, the example is not realizable (I wonder whether `ENVINIT` is wrong, but it is irrelevant to the issues here and to realizability).

Checked this with a dev version of `omega == 0.0.10`:

```python
from omega.games import gr1
from omega.symbolic import symbolic

a = symbolic.Automaton()
a.moore = False
a.plus_one = False
a.qinit = '\A \A'
a.vars['x'] = dict(type='bool', owner='env')
a.vars['y'] = dict(type='bool', owner='sys')
a.init['env'] = ['True']
a.init['sys'] = ['True']
a.action['env'] = ["True"]
a.action['sys'] = ["y' <=> x"]
a.win['<>[]'] = ["!x"]
a.win['[]<>'] = ["!y"]
aut = a.build()
z, _, _ = gr1.solve_streett_game(aut)
assert not gr1.is_realizable(z, aut)
```

The example was intended to be unrealizable, so that realizability be only due to the initial condition.

**Comment by slivingston** [comment]
Now I understand the significance of your original post.

As for behavior of `gr1c`, I think that the most useful behavior is, when `Init \equiv FALSE`,
* declare that the specification is not realizable;
* tell the user that `Init \equiv FALSE`, or equivalently, that there are no states that satisfy initial conditions.

**Comment by slivingston** [comment]
@johnyf In terms of your original post, I am suggesting [above](https://github.com/tulip-control/gr1c/issues/27#issuecomment-253049306) to modify the definition. My motivation is synthesis, i.e., the production of some strategy that is a witness for realizability.

Otherwise, if we regard the specification as realizable (and thus, do not modify the first definition in the OP), then we must be able to produce some strategy. Should it be empty? Should it contain a single node and a self-loop? Should it be some strategy that provides liveness and safety, but begins at some arbitrarily chosen initial states, if possible? Though we can argue about possibilities, they all involve some additional assumptions about how a strategy would be used.

**Comment by johnyf** [comment]
Thanks for applying this change. I think that it addresses the issue. It is the counterpart of `tulip.spec.GRSpec.plus_one`.

**Comment by slivingston** [comment]
I want to acknowledge that you sent me additional material via email that is relevant to this issue. I am going to consider it soon and, possibly, re-open this issue and add salient details here.
