### ISSUE TITLE
make cudd fails

### ISSUE THREAD

**Issue by dathath** [tulip-control/gr1c#32]
As of commit 634db27ea52935f827be33d5ce4409ceeab0b306,  $make cudd
during install prompts the error
"make: *** No rule to make target 'cudd'.  Stop."

Older commits (eg. 5beb71e9b6d05b2b8c59d85d2fb58f8905fde89a) do not suffer from this issue.

**Comment by slivingston** [comment]
try

    ./build-deps.sh

**Comment by slivingston** [comment]
the summary of install commands in the README is out-of-date, but the installation instructions ([doc/installation.md](https://github.com/tulip-control/gr1c/blob/634db27ea52935f827be33d5ce4409ceeab0b306/doc/installation.md#building) should be correct.

**Comment by slivingston** [comment]
@dathath if you can confirm that `build-deps.sh` and otherwise using the installation instructions in the User Manual, then I will update the README and close this issue.

**Comment by slivingston** [comment]
I updated the README. Please reopen this issue if I missed something.
