### ISSUE TITLE
Installing gr1c on Windows

### ISSUE THREAD

**Issue by abadithela** [tulip-control/gr1c#34]
I'm new to using TuLiP. I'm trying to install gr1c but I don't think it works with Windows. Should I use a VM? Could you please advise on how I should proceed?

**Comment by slivingston** [comment]
@abadithela is this issue still open for you ?

**Comment by slivingston** [comment]
related issue: https://github.com/tulip-control/tulip-control/issues/197

**Comment by slivingston** [comment]
also related: #35

**Comment by abadithela** [comment]
Hi Scott, Yes, this is still an issue for me. However, I'm able to use most TuLiP functions without gr1c.

**Comment by slivingston** [comment]
I am going to re-open this issue because it is not actually solved if you are not using `gr1c`.

**Comment by slivingston** [comment]
As of commit 3287935d895c8847b0a3e989a2b8e2b173b46b23, gr1c can be cross-compiled for Windows from GNU/Linux hosts. The commit message has a summary of instructions, which I will expand and put in the documentation.

I tried several examples both for `gr1c` and `gr1c rg`, all of which gave output that has no obvious error. However, I have performed some but not all tests. I am working to port the testing suite now.

**Comment by slivingston** [comment]
@abadithela I built gr1c for Windows. If you have an opportunity, I would greatly appreciate your feedback. Built executables are available at <https://github.com/tulip-control/gr1c/releases/download/v0.13.0/gr1c-0.13.0-Win64.zip> (part of the [new release](https://github.com/tulip-control/gr1c/releases/tag/v0.13.0)).

**Comment by slivingston** [comment]
no reported errors since the release.
